# What are NumPy arrays?
The NumPy library is the core library for scientific computing using Python. Scientists who use large datasets (us!) like to use NumPy because it has good tools for working with high dimensional arrays.

### Starting with 1D arrays
![1D array](https://www.dyclassroom.com/image/topic/java/array/1d/1d-array.jpg)

In [3]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


Review: 
1. Write the code that will print the number '4':
2. Write the code that will create and print an array with 3, 4, 5 

In [4]:
# 1.

In [14]:
# 2. 

## What about 2D arrays? And 3D arrays?
![3D](https://www.oreilly.com/library/view/elegant-scipy/9781491922927/assets/elsp_0105.png)

# Here are some visuals to help you understand numpy arrays better


### We'll first create a 4x5 array. 

In [2]:
import numpy as np
b=np.arange(1,60,3)
a = np.arange(1,60,3).reshape(4,5)
print(a)
print(b)

[[ 1  4  7 10 13]
 [16 19 22 25 28]
 [31 34 37 40 43]
 [46 49 52 55 58]]
[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58]


Our array, a, looks like this: 

![image](https://raw.githubusercontent.com/amnh/BridgeUP-STEM-Oceans-Six/master/photos/Screen%20Shot%202018-11-02%20at%205.23.03%20PM.png?token=AmUbDpWjSe4asRuC415N-d381PDnMuTAks5b7ahPwA%3D%3D)


Now, what if we want to select a part of this array? For example, we want to select the element '25'? 

In [2]:
a[1,3]

25

It can help to think of your selection as an intersection of indices.

![image](https://raw.githubusercontent.com/amnh/BridgeUP-STEM-Oceans-Six/master/photos/Screen%20Shot%202018-11-02%20at%205.40.45%20PM.png?token=AmUbDh80CPWOXWsxehydto2v0jYHJcWGks5b7ah5wA%3D%3D)

Now, let's try selecting just the first row.

In [3]:
a[0,:]

array([ 1,  4,  7, 10, 13])

![image](https://raw.githubusercontent.com/amnh/BridgeUP-STEM-Oceans-Six/master/photos/firstrow.png?token=AmUbDqPS-gD5MuRbGX9qog99B0RbkvFMks5b7aiNwA%3D%3D)

What if we want to select the fifth column? 

In [5]:
a[:,4]

array([13, 28, 43, 58])

![image](https://raw.githubusercontent.com/amnh/BridgeUP-STEM-Oceans-Six/master/photos/lastcolumn.png?token=AmUbDsXOpKqJbn9QlEKgnIcbXtXsaoUAks5b7aibwA%3D%3D)

Now, what if we want to select part of a column or row? Here is where the colon notation gets tricky.

I want to return the elements '22' and '37', in their own array. Using colon notation can return a range of values. 

However, Python uses what we call an "uninclusive" range. The last number in any user-specified range is not included, by default.

For example, using the "range" function, such as `range(0, 10)`, returns the numbers 0 through 9. 

In [15]:
for i in range(0,10):
    print(i)

0
1
2
3
4
5
6
7
8
9


How do we select '22' and '37'? What is the intersection we're looking for?

In [16]:
a[1,2:5]

array([22, 25, 28])

![image](https://raw.githubusercontent.com/amnh/BridgeUP-STEM-Oceans-Six/master/photos/partofcolumn.png?token=AmUbDuIihl2TPdYe2k_HE-ytjShglXQ3ks5b7aiswA%3D%3D)

# Practice: 
1. Create 2 dimensional array with dimensions 3 x 4, containing numbers 1-12
2. Print the first row of this array. 
3. Print the number 10
4. Print the second column of this array

In [10]:
# 1. 

In [11]:
# 2. 

In [12]:
# 3. 

In [13]:
# 4. 

![image](https://www.trzcacak.rs/file/max/96/964354_white-divider-line-png.png)

## What about 3D arrays?
### We'll first create a 2x2x5 array.

In [20]:
a = np.arange(1,60,3).reshape(2,2,5)

`a = array([[[ 1,  4,  7, 10, 13],
        [16, 19, 22, 25, 28]],`

       [[31, 34, 37, 40, 43],
        [46, 49, 52, 55, 58]]])
        
Graphically, it looks like this. 
![image](https://raw.githubusercontent.com/amnh/BridgeUP-STEM-Oceans-Six/master/photos/Screen%20Shot%202018-11-02%20at%206.14.07%20PM.png?token=AmUbDrtNU8p2FFYj4UNlh7hBvBuiEt0bks5b7ajGwA%3D%3D)
The array has 2 groups, which each have two rows and 5 columns.

Suppose we want to select the values 31 and 46. What is the intersection that produces these values?

In [22]:
a[1,:,0]

array([31, 46])

![image](https://raw.githubusercontent.com/amnh/BridgeUP-STEM-Oceans-Six/master/photos/Screen%20Shot%202018-11-02%20at%206.21.08%20PM.png?token=AmUbDmk8JrWSOYRqc2SlBxQsn7RpJKkxks5b7ajbwA%3D%3D)

## Some more challenges

In [6]:
c = np.arange(1,72,3).reshape(2,3,4)
print(c)

[[[ 1  4  7 10]
  [13 16 19 22]
  [25 28 31 34]]

 [[37 40 43 46]
  [49 52 55 58]
  [61 64 67 70]]]


In table form, this array looks like this: 
![image](https://raw.githubusercontent.com/amnh/BridgeUP-STEM-Oceans-Six/master/photos/Screen%20Shot%202018-11-07%20at%2011.28.01%20AM.png?token=AmUbDkvrUr9WOl3dMf3WN4OD_tu96Yeiks5b7ajvwA%3D%3D)

1. What code can you write to return the value '49'?
2. What code can you write to return the third row in the first group?
3. What code can you write to return the values '55' and '58'?

If you're stuck, think about the intersections required to find each one of these values! What combination of rows, columns and groups are necessary?

In [9]:
# 1. 

In [8]:
# 2. 

In [7]:
# 3. 

![divider](https://www.trzcacak.rs/file/max/96/964354_white-divider-line-png.png)

### Cheat sheet/Some general tips to select the appropriate part of the array:

In [16]:
# Remember, all arrays begin at the 0 index! So a[0] picks the first element, a[1] picks the *second*, and so on

#1D arrays
a[:] # This command selects everything
a[2:5] # This commands selects the 2nd through the 4th rows (does not include the 5th row).
    #The numbers inside the brackets can be changed to select whatever elements you want. 

    
#2D arrays
b[:,:] #This command selects all rows and all columns
b[:,0] #This command selects all rows, and the zeroth column
b[0,:] #This command selects the zeroth row, and all columns in that row
b[0:2,:] #This column selects the zeroth and first row, but NOT the second. It includes all the columns in that row

#3D arrays
c[:,:,:] #This command selects everything.
# Technically, the first dimension is known as the row, the second as column and the third as depth... 
#but I find that confusing. We'll call the first dimension the "group," the second "row," and third, "column" (as usual).
c[0,:,:] #This command selects the 0th group, and all rows/columns in that group
c[:,0,:] #This command selects the 0th row from every group
c[:,:,0] #This command selects the 0th row from every group
c.shape #Tells you the shape of your array. The first value is the size of the first dimension, and so on

NameError: name 'b' is not defined