There are a few ways to loop through lists and arrays. The first one is the way you probably are the most familiar with:

In [18]:
my_list = ['cat','dog','bird','fish','hampster']
# make your own list of whatever you want here:

#

In [3]:
for item in my_list:
    print(item)

cat
dog
bird
fish
hampster


In [32]:
# do this with your list just for practice: 


You can use this method to loop through a numpy array as well:

In [20]:
import numpy as np
my_array = np.arange(0,10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
for item in my_array:
    print(item)

0
1
2
3
4
5
6
7
8
9


Does this work for 2-d arrays as well? Try it:

In [10]:
# make a 2-D numpy array of any shape:


In [11]:
# Loop through it: 


The other way to loop through a list is to loop through the **indicies** of a list and call each item by its index. Here is an example:

In [12]:
for i in range(0,5): # we use 5 because there are 5 elements in the list
    print(my_list[i])

cat
dog
bird
fish
hampster


Try this with the list you made in the first cell:

In [19]:
#try it here:


This works for 2-dimensional lists and arrays as well. In this case you need to loop through each dimension: 

In [30]:
my_2d_array = np.arange(0,12*4,4).reshape(3,4)
print(my_2d_array)

[[ 0  4  8 12]
 [16 20 24 28]
 [32 36 40 44]]


In [28]:
for i in range(0,3): #first we are looping through three rows
    for j in range(0,4): #then in each row we are looping through 4 columns
        print(my_2d_array[i,j])

0
1
2
3
4
5
6
7
8
9
10
11


This is called a **nested loop** because there is one loop inside of another.  

Let's think about why this works. First, let's print the list of indices:

In [29]:
for i in range(0,3):
    for j in range(0,4): 
        print(i,j)

0 0
0 1
0 2
0 3
1 0
1 1
1 2
1 3
2 0
2 1
2 2
2 3


Now, on paper, go through the list of printed indices and get the element at each index. This should take a few minutes. 

------
Finally, we are going to put this together for 3-d arrays. First we need to define a 3-d array:

In [31]:
# Do that here


Now we are going to loop through each dimension using a nested loop. Think about what you need to loop through on each dimension. 

In [33]:
# Do that here


That's it! Now you're ready to apply this to our project. 